### ISSUE TITLE
BOM Extraction Functionality

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/WebDMS2#1]
Create Context Menu at Folder Level to initiate Box Extraction (stored in LN upto Part level). The extraction will be done for latest drawings in the excel format (refer Excel Maintained by YNR for SAP entry)

Action By: @0340LalitGupta 
Review By: @veena-isgec

**Comment by 0340LalitGupta** [comment]
Delivered. Developed functionality is OK. Issue can be closed. @hariharan-isgec

**Comment by 0340LalitGupta** [comment]
Functionality showed to YNR.  If any modification is needed new case can be created.
This requirement can be closed. @hariharan-isgec
